# Default values for playground-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
airflow:
  # Default airflow repository -- overridden by all the specific images below
  defaultAirflowRepository: apache/airflow
  # Default airflow tag to deploy
  defaultAirflowTag: "2.8.3"

  defaultAirflowDigest: ~
  # Path where dags are mounted. If using minikube makesure this path is mounted to container from hostPath.
  dagpvcMountPath: /opt/dags
  dags:
  # Where dags volume will be mounted. Works for both persistence and gitSync.
  # If not specified, dags mount path will be set to $AIRFLOW_HOME/dags
    mountPath: ~
    persistence:
      # Annotations for dags PVC
      annotations: {}
      # Enable persistent volume for storing dags
      enabled: true
      # Volume size for dags
      size: 1Gi
      # If using a custom storageClass, pass name here
      storageClassName:
      # access mode of the persistent volume
      accessMode: ReadOnlyMany
      ## the name of an existing PVC to use
      existingClaim: dag-load-pvc
      ## optional subpath for dag volume mount
      subPath: ~

spark:
  warehouseDir: "s3a://spark-warehouse/warehouse"

replicaCount: 1
minio-operator:
  enabled: false
minio-tenant:
  enabled: true
image:
  repository: nginx
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
# For airflow subchart
# postgresql:
#   enabled: true

# postgresql:
#   enabled: true
#   auth:
#     enablePostgresUser: true
#     postgresPassword: postgres
#     username: ""
#     password: ""

postgresql:
  enabled: true
  global:
    postgresql:
      auth:
        username: postgres
        password: postgres
        database: metastore

  # For easy deployment don't use persistent volumes. Obviously, not proper
  # for production release
  primary:
    persistence:
      enabled: false

    # The apache hive docker image has an jdbc driver that doesn't use the latest encruption
    # settings. Tell postgres to allow access any way
    extendedConfiguration: |-
      password_encryption=md5
